apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal
  labels:
    app: minimal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: minimal
  template:
    metadata:
      labels:
        app: minimal-api
        service: minimal
    spec:
      containers:
        - name: minimal
          image: pedrovala/minimalapi:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: minimal
  labels:
    app: minimal-api
    service: minimal
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: minimal